server:
  port: 8000

spring:
  application:
    name: api-gateway
  jwt:
    signerkey: ${JWT_SECRET}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-public-route
              uri: lb://Account-Service
              predicates:
                - Path=/api/auth/**

            - id: user-secured-route
              uri: lb://Account-Service
              predicates:
                - Path=/api/users/**

            - id: product-route
              uri: lb://Product-Service
              predicates:
                - Path=/api/products/**

            - id: category-route
              uri: lb://Product-Service
              predicates:
                - Path=/api/categories/**

            - id: payment-route
              uri: lb://Payment-Service
              predicates:
                - Path=/api/orders/**

            - id: media-route
              uri: lb://Media-Service
              predicates:
                - Path=/api/media/**

            - id: chatbot-route
              uri: lb://AI-Service
              predicates:
                - Path=/api/chatbot/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}