apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: app-secrets
    envs:
      - ../.env
    options:
      disableNameSuffixHash: true

resources:
  - postgres.yaml
  - account-service.yaml
  - api-gateway.yaml
