apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    CREATE DATABASE "fashion-account-service";
    GRANT ALL PRIVILEGES ON DATABASE "fashion-account-service" TO app_user;
---
apiVersion: v1
kind: PersistentVolumeClaim # Class
metadata:
  name: postgres-pvc # Object name
spec: # Constructor params
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-init-volume
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-volume
          configMap:
            name: postgres-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: ClusterIP