spring.application.name=Payment-Service
server.port=8083

spring.jwt.signerkey=${JWT_SECRET:isxtj7Ez9VtK5s8+/jWnbGUAzo+/LaHlz8Py+7gT07bwtMSV3yfKDkNvDnfKoevA}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/fashion-payment-service
spring.datasource.username=${POSTGRES_USER:app_user}
spring.datasource.password=${POSTGRES_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true

# Product Service Endpoint
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}

# PayPal Configurations (Sandbox Credentials defaults)
paypal.client.id=${PAYPAL_CLIENT_ID:AZHUN6GO8x08aEMFgFKoGD5FjJnuTrd7BKf-YR-8D-1II0xuKyB_g4NMBWf70LWR_r94QgKgxJ5HtKJi}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:EOwM1OcMkw6j0oAKdwuEYwC8QUvwGiDbc8PQlYtuMP0autnVNmaiL4-dH7BccQA2EiQ6FucfFugyOBGg}
paypal.mode=${PAYPAL_MODE:sandbox}
paypal.exchange-rate=${PAYPAL_EXCHANGE_RATE:25000.0}

