spring.application.name=AI-Service
server.port=8085

spring.jwt.signerkey=${JWT_SECRET:isxtj7Ez9VtK5s8+/jWnbGUAzo+/LaHlz8Py+7gT07bwtMSV3yfKDkNvDnfKoevA}

# Gemini API Endpoint Config
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-lite:generateContent
gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6II_sfuewxtVsNi-KXlR7ZBQUURvH5TpRH9DLT4LY2VmQ}

# Product Service Endpoint for fetching product details dynamically
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}
