spring.application.name=AI-Service
server.port=8085

spring.jwt.signerkey=${JWT_SECRET}

# Gemini API Endpoint Config
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-lite:generateContent
gemini.api.key=${GEMINI_API_KEY}

# Product Service Endpoint for fetching product details dynamically
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
