spring.application.name=Media-Service
server.port=8084

spring.jwt.signerkey=${JWT_SECRET:isxtj7Ez9VtK5s8+/jWnbGUAzo+/LaHlz8Py+7gT07bwtMSV3yfKDkNvDnfKoevA}

# File Upload configurations
file.upload-dir=${FILE_UPLOAD_DIR:./uploads}

# Increase upload size limits in Spring Boot
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
